AWStemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31 #Especifica que esta plantilla sera de SAM

Resources:
  MyResource01:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: comoquieran/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        MyEvent01:
          Type: Api
          Properties:
            Path: /articles
            Method: get


